import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="flex items-center justify-around bg-slate-100 px-6 py-4">
  <p className="font-Montserrat font-bold text-[24px]">Bandage</p>
  <div className="flex items-center space-x-4">
    <Image src={"/facebook.png"} alt="Facebook" width={26} height={26} />
    <Image src={"/instagram.png"} alt="Instagram" width={26} height={26} />
    <Image src={"/twitter.png"} alt="Twitter" width={26} height={26} />
  </div>
</div>
        
        <footer className=" text-black py-6">
    <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 md:grid-cols-5 gap-8">
            <div className="col-span-1">
                <h2 className=" font-bold mb-4 font-Montserrat  text-base">Company Info</h2>
                <ul className="font-Montserrat font-bold text-sm text-gray-600">
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Carrier</a></li>
                    <li><a href="#">We are hiring</a></li>
                    <li><a href="#">Blog</a></li>
                </ul>
            </div>
            <div className="col-span-1">
                <h2 className=" font-bold mb-4 font-Montserrat text-base">Legal</h2>
                <ul className="font-Montserrat font-bold text-sm text-gray-600">
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Carrier</a></li>
                    <li><a href="#">We are hiring</a></li>
                    <li><a href="#">Blog</a></li>
                </ul>
            </div>
            <div className="col-span-1">
                <h2 className=" font-bold mb-4 font-Montserrat text-base">Features</h2>
                <ul className="font-Montserrat font-bold text-sm text-gray-600">
                    <li><a href="#">Business Marketing</a></li>
                    <li><a href="#">User Analytic</a></li>
                    <li><a href="#">Live Chat</a></li>
                    <li><a href="#">Unlimited Support</a></li>
                </ul>
            </div>
            <div className="col-span-1">
                <h2 className="font-Montserrat text-base font-bold mb-4">Resources</h2>
                <ul className="font-Montserrat font-bold text-sm text-gray-600">
                    <li><a href="#">iOS & Android</a></li>
                    <li><a href="#">Watch a Demo</a></li>
                    <li><a href="#">Customers</a></li>
                    <li><a href="#">API</a></li>
                </ul>
            </div>
            <div className="col-span-1">
                <h2 className="font-Montserrat text-base font-bold mb-4">Get In Touch</h2>
                
                <div className="mb-4">
          <div className="flex items-center ">
            <input
              type="email"
              placeholder="Your Email"
              className="w-auto border border-gray-300 p-2 rounded"
            />
            <button className="bg-blue-400 py-2 px-1 rounded hover:bg-blue-100">
              Subscribe
            </button>
          </div>
          <p className="text-sm mt-2 font-Montserrat font-normal text-[12px]">Lorem ipsum dolor sit amet.</p>
        </div>
      </div>
    </div>
        </div>
        <div className="text-center mt-6 font-Montserrat font-bold text-sm text-gray-600">
            <p>Made With Love By Finland | All Rights Reserved</p>
        </div>
    
</footer>


      </body>
    </html>
  );
}
